home/urls.py
from .views import index, submit_tanaman, app
from django.urls import path, re_path

app_name = "home"
urlpatterns = [
  path('', app, name="index"),
  path('app/', index, name="app"),
  path('tanaman/', submit_tanaman, name="submit_tanaman")
]

load_csv/urls.py
from django.urls import path
from .views import *

urlpatterns = [
  path('', load)
]

tanamin/urls.py
from django.urls import path, include, re_path
from django.contrib import admin
import load_csv.urls as load_csv
import home.urls as home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('load-csv/', include(load_csv)),
    re_path(r'^', include(home, namespace="home"))
]

csp/models.py
from django.db import models
from load_csv.models import Province
# Create your models here.
class ProvinceNeighbors(models.Model):
  province = models.ForeignKey(Province, on_delete=models.CASCADE)
  neighbor = models.ForeignKey(Province, on_delete=models.CASCADE, related_name="neighbor", null=True)

  class Meta:
    unique_together = ("province", "neighbor")

home/models.py
from django.db import models

# Create your models here.

load_csv/models.py
from django.db import models

# Create your models here.
class Province(models.Model):
  name = models.CharField(max_length=20, unique=True)
  area = models.FloatField()

csp/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render, reverse, redirect
from load_csv.models import Province as ProvinceModel
from csp.models import ProvinceNeighbors
from csp.utils import Color, Province, Graph, Csp, LocalSearch

# Create your views here.
def index(request):
	return render(request, 'index.html')

def submit_tanaman(request):
	if request.method == 'POST':
		input = request.POST.getlist('tanamans')
		# print(input)
		# form = UnknownForm()
		jumlah = len(input)
		tanamans = input
		colors = []
		graph = Graph()
		for i in range(int(jumlah)):
			colors.append(Color(i + 1, tanamans[i]))
		for obj in ProvinceNeighbors.objects.all().iterator():
			prov = Province(name=obj.province.name, area=obj.province.area)
			if obj.neighbor:
				graph.add_edge(prov, Province(name=obj.neighbor.name, area=obj.neighbor.area))
			else:
				graph.add_edge(prov)
			
		csp = Csp(graph, colors)
		local_search = LocalSearch(csp, jumlah)

		a = {plant:0 for plant in tanamans}
		r,c = local_search.min_conflicts()
		if c % 2 != 0:
			c += 1
		for i in r:
			a[r[i].color.plant] += r[i].area
				
	return render(request,'index.html', {"dictionary":r, "luas_pangan": a, 'conflicts': c//2})
	
def app(request):
	return render(request, "landing.html")

load_csv/views.py
from django.shortcuts import render
import csv, os
from functools import reduce
import math
from .models import Province
from tanamin.settings import BASE_DIR
from csp.models import ProvinceNeighbors

# Create your views here.
def load(request):
  Province.objects.all().delete()
  ProvinceNeighbors.objects.all().delete()
  with open(os.path.join(BASE_DIR, 'data.csv')) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=';')
    next(csv_reader, None)

    provinces = [province for province in csv_reader]
    areas = [int(province[1]) for province in provinces]
    names = [province[0] for province in provinces]
    neighbors = [province[2] for province in provinces]
    
    province_with_areas = [[names[i], areas[i], neighbors[i]] for i in range(len(areas))]
    province_with_areas.sort(key=lambda x: x[1], reverse=True)

    for name, area, neighbors in province_with_areas:
      pro = Province(name=name, area=area)
      pro.save()
    for name, area, neighbors in province_with_areas:
      for ngbr_name in neighbors.split(", "):
        curr = Province.objects.get(name=name)
        if ngbr_name != "":
          print(ngbr_name)
          ngbr_obj = Province.objects.get(name=ngbr_name)
          conn_obj = ProvinceNeighbors(province=curr, neighbor=ngbr_obj)
        else:
          conn_obj = ProvinceNeighbors(province=curr, neighbor=None)
        conn_obj.save()

  return render(request, "table.html", {"data_provinsi": province_with_areas})

home/templates/footer.html
{% load static %}
<footer class="footer">
    <div class="container">
    <span class="text-muted">&copySCBD - Sistem Cerdas C</span>
    <br>
    <a href="https://gitlab.com/fariqodri/tanamin_sc"><i class="fa fa-gitlab"></i></a>
    </div>
</footer>

home/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/tanamin.css' %}">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/agency.css' %}" rel="stylesheet">

{% endblock %}
{% block content %}
<div class="se-pre-con"></div>
<nav class="navbar navbar-expand-lg navbar-shrink navbar-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="/">tanamin</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ml-auto">
            <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="/">Home</a>
            </li>
            <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="/app">aplikasi</a>
            </li>
        </ul>
        </div>
    </div>
</nav>
<div>
    {% for key, value in dictionary.items %}
        <li class="data">{{ value.name }}</li>
        <li class="data">,</li>
        <li class="data">{{ value.color.num }}</li>
        <li class="data">,</li>
        <li class="data">{{ value.color.plant }}</li>
        <li class="data">;</li>
    {% endfor %}
    <h2 class="data jumlah">{{tanamans}}</h2>
</div>
    <section class="map" id="map" style="margin-top: -80px;">
        <div class="container-fluid">
            <div class="row"> 
                <div class="col-lg-2">
                    <div class="card">
                <h5 class="card-header">Form Input User</h5>
                <div class="card-body">
                    <form action="{% url 'home:submit_tanaman' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-check">
                            <div class="col-md">
                                <!-- <small class="form-text text-muted">
                                    format: [Jumlah Jenis Tanaman]_[Jenis Tanaman 1]_[Jenis Tanaman n]
                                </small>
                                <small class="form-text text-danger">
                                    Warning: semakin banyak atau sedikit tanaman yang diberikan, semakin lama proses searching akan berjalan.
                                    Jika angka yang diberikan terlalu banyak atau sedikit, maka proses mungkin gagal
                                </small>
                                <small class="form-text text-success">
                                    Jumlah yang disarankan: 4-6
                                </small>
                                <small class="form-text text-muted">
                                    contoh: 4_padi_tebu_jagung_teh
                                </small> -->
                                <!-- <label for="tanaman">Jumlah dan Jenis Tanaman <small>(minimal 4 jenis tanaman)</small></label>
                                <input type="text" id="tanaman" class="form-control" name="tanamans"> -->
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="tanamans" value="Cengkeh" id="defaultCheck1">
                                    <label class="form-check-label" for="defaultCheck1">
                                        Cengkeh
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="tanamans" value="Jagung" id="defaultCheck2">
                                    <label class="form-check-label" for="defaultCheck2">
                                        Jagung
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="tanamans" value="Kelapa Sawit" id="defaultCheck3">
                                    <label class="form-check-label" for="defaultCheck3">
                                        Kelapa Sawit
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="tanamans" value="Kopi" id="defaultCheck4">
                                    <label class="form-check-label" for="defaultCheck4">
                                        Kopi
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="tanamans" value="Padi" id="defaultCheck5">
                                    <label class="form-check-label" for="defaultCheck5">
                                        Padi
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="tanamans" value="Tebu" id="defaultCheck6">
                                    <label class="form-check-label" for="defaultCheck6">
                                        Tebu
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="tanamans" value="Teh" id="defaultCheck7">
                                    <label class="form-check-label" for="defaultCheck7">
                                        Teh
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="tanamans" value="Tembakau" id="defaultCheck8">
                                    <label class="form-check-label" for="defaultCheck8">
                                        Tembakau
                                    </label>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary my-1">Submit</button>
                    </form>
                </div>
            </div>
                </div>
                <div class="col-lg-8">
                    <div id="geochart" style="width: 100%;"></div>
                </div>
                <div class="col-lg-2">
                    <ol>
                        Persebaran Pangan:
                        {% for key, value in luas_pangan.items %}
                        <li>
                            {{key}}: {{value}}
                        </li>
                        {% endfor %}
                        Conflicts: 
                        {{conflicts}}
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <br>
    
    <!-- Geo Chart -->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="{% static 'js/geochart.js' %}"></script>

    <!-- Bootstrap core JavaScript -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

<!-- Plugin JavaScript -->
<script src="{% static 'js/jquery.easing.js'%}"></script>
<script src="{% static 'js/test.js' %}"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
<script>
$(window).load(function() {
		// Animate loader off screen
		$(".se-pre-con").fadeOut("slow");;
	});
</script>
	
 {% endblock %}

home/templates/landing.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<!-- Custom fonts for this template -->
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

<!-- Custom styles for this template -->
<link href="{% static 'css/agency.css' %}" rel="stylesheet">
<style>
  .text-biasa {
    color:rgb(230, 170, 75);
  }
  .text-biasa .text-tanamin{
    font-family: 'Droid Serif', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  }
  .halaman .container{
    top: 40%;
}

p .npm{ 
	font-family: Courier New,Courier,Lucida Sans Typewriter,Lucida Typewriter,monospace; 
}

</style>
{% endblock %}
{% block content %}
{% include 'navbar.html' %}
      <!-- Header -->
      <header class="masthead">
        <div class="container">
          <div class="intro-text">
            <div class="hh intro-heading text-uppercase">tanamin</div>
            <a class="hh btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#apa">Pelajari</a>
          </div>
        </div>
      </header>
  
      
      <section id="apa" class="halaman">
        <div class="container">
            <div class="col-md-7">
                <h1>Apa itu <em class="text-biasa text-tanamin">tanamin</em> ?</h1>
                <p><span class="text-biasa text-tanamin">Tanamin</span> merupakan sebuah website <span class="text-biasa">pemetaan produksi pangan</span>
                    berdasarkan provinsi yang ada di Indonesia.</p>
                <p>Kamu dapat memberikan masukan jenis-jenis
                    pangan yang ingin dipetakan secara <span class="text-biasa">merata</span>, lalu <span class="text-biasa text-tanamin">tanamin</span> akan membuatnya <span class="text-biasa">merata</span>!</p>
            </div>
        </div>
      </section>

      <section id="bagaimana" class="halaman">
          <div class="se-pre-con"></div>
          <div class="container">
            <div class="row">
                <div class="col-md-5">
                  </div>
                  <div class="col-md-7" style="text-align:right;">
                      <h1>Bagaimana <span class="text-biasa text-tanamin">tanamin</span> bekerja?</h1>
                      <p><span class="text-biasa text-tanamin">Tanamin</span> adalah agent yang dibuat untuk menyelesaikan <span class="text-biasa">CSP</span> (Constraint Satisfaction Problem). Constraints berupa <span class="text-biasa">warna</span> dari provinsi yang
                          bersebelahan <span class="text-biasa text-tanamin">tidak boleh sama</span> dan <span class="text-biasa">jumlah luas</span> dari provinsi yang memproduksi suatu jenis
                          pangan tidak boleh berbeda <span class="text-biasa text-tanamin">terlalu jauh</span>.</p>
                  </div>
            </div>
          </div>
        </section>


      <!-- Services -->
      <section id="tim" class="halaman">
        <div class="container">
          <h1 class="text-center profil">Developer <span class="text-biasa text-tanamin">Tanamin</span></h1>
          <br>
          <div class="row text-center">
            <div class="col-md-4 profil">
              <h4 class="service-heading">Fari Qodri A.</h4>
              <p class="text-muted npm">1606875964</p>
            </div>
            <div class="col-md-4 profil">
              <h4 class="service-heading">Indra Septama</h4>
              <p class="text-muted npm">1606892296</p>
            </div>
            <div class="col-md-4 profil">
              <h4 class="service-heading">Priambudi Lintang B.</h4>
              <p class="text-muted npm">1606895171</p>
            </div>
          </div>
        </div>
        <br>
        <br>
        <div class="col-lg-12 text-center">
            <a class="btn btn-primary btn-xl text-uppercase" href="/app">Mulai!</a>
          </div>
      </section>
  
<!-- Bootstrap core JavaScript -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

<!-- Plugin JavaScript -->
<script src="{% static 'js/jquery.easing.js'%}"></script>

<!-- Custom scripts for this template -->
<script src="{% static 'js/agency.js' %}"></script>
<script src="{% static 'js/test.js' %}"></script>
<script src="{% static 'js/parallax.min.js' %}"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
<script src="https://unpkg.com/scrollreveal@4"></script>
<script>
  var slideLeft = {
    distance: '150%',
    origin: 'right',
    reset: true,
    duration: 2000,
    opacity: null
  };

  var slideRight = {
    distance: '150%',
    origin: 'left',
    useDelay: 'onload',
    reset: true,
    duration: 2000,
    opacity: null
  };

  var slideUp = {
    useDelay: 'onload',
    reset: true,
    duration: 2000,
    interval: 300,
    opacity: 0
  };
$(window).load(function() {
  $(".se-pre-con").fadeOut("slow");
});
ScrollReveal().reveal('#apa', slideRight);
ScrollReveal().reveal('#bagaimana', slideLeft);
ScrollReveal().reveal('.profil', slideUp);
</script>
{% endblock %}

home/templates/navbar.html
{% load static %}
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">tanamin</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fa fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#apa">apa</a>
          </li>
          <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#bagaimana">bagaimana</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#tim">Tim kami</a>
              </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="/app">aplikasi</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

load_csv/templates/table.html
{% extends 'base.html' %}

{% block content %}
  <h3>CSV berhasil di-load ke database</h3>
  <table class="table">
    <thead>
      <th scope="col">Nama Provinsi</th>
      <th scope="col">Luas Provinsi (Feature Scaled)</th>
      <th scope="col">Provinsi Tetangga</th>
    </thead>
    <tbody>
      {% for data in data_provinsi %}
        <tr>
          <td>{{data.0}}</td>
          <td>{{data.1}}</td>
          <td>{{data.2}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="description" content="This is a final project for Intelligent System subject by SCBD team">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>tanamin</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon (1).ico'%}"/>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  

  {% block css %}
  {% endblock %}
</head>
{% block body %}
<body id="page-top">
  {% block content %}
  {% endblock %}
  </body>
{% endblock %}
{% include 'footer.html' %}
</html>